apiVersion: v1
kind: Service
metadata:
 name: lolfrontend
spec:
 selector:
   role: frontend
 ports:
   - protocol: TCP
     port: 80
     targetPort: 80
     nodePort: 32080
 type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
 name: frontend-deployment
 labels:
   role: frontend
spec:
 replicas: 3
 selector:
   matchLabels:
     role: frontend
 template:
   metadata:
     labels:
       role: frontend
   spec:
     containers:
     - name: frontend-app
       image: "timmillergcpuser/test-webapp-frontend:0.2d3"
---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: basic-ingress
spec:
  backend:
    serviceName: frontend
    servicePort: 80
